/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./*.html",
    "./products/**/*.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bdc6e1",
        "on-primary-fixed": "#121b2f",
        "surface-tint": "#555e76",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-container-high": "#dce9ff",
        "cad-blue": "#334155",
        "secondary": "#895100",
        "on-secondary-fixed-variant": "#683d00",
        "on-background": "#0b1c30",
        "secondary-fixed-dim": "#ffb86b",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdcbd",
        "on-secondary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "inverse-surface": "#213145",
        "primary": "#000000",
        "deep-navy": "#020617",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
        "secondary-container": "#fd9d1a",
        "on-surface": "#0b1c30",
        "on-primary-container": "#7a849d",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#3d475d",
        "safety-orange": "#F97316",
        "tertiary-container": "#2b1703",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-container": "#663b00",
        "on-tertiary-fixed-variant": "#5b4227",
        "on-tertiary-container": "#9e7e5f",
        "surface-variant": "#d3e4fe",
        "tertiary": "#000000",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#2c1700",
        "tertiary-fixed-dim": "#e5c09d",
        "slate-surface": "#F8FAFC",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#ffdcbc",
        "inverse-primary": "#bdc6e1",
        "on-tertiary": "#ffffff",
        "outline": "#76777d",
        "on-surface-variant": "#45464d",
        "on-tertiary-fixed": "#2b1703",
        "outline-variant": "#c6c6cd",
        "surface": "#f8f9ff",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "primary-container": "#121b2f",
        "primary-fixed": "#d9e2fe",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "technical-data": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "technical-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
